from __future__ import annotations

from collections.abc import AsyncIterator, Awaitable, Callable
from typing import Any, Protocol


class SttSession(Protocol):
    async def connect(self) -> None: ...
    async def send_audio(self, data: bytes) -> None: ...
    async def send_keepalive(self) -> None: ...
    async def close(self) -> None: ...
    def events(self) -> AsyncIterator[dict[str, Any]]: ...


EventCallback = Callable[[dict[str, Any]], Awaitable[None]]
